bindings/cpu_profiler.cc, package-lock.json, package.json, playground/express/index.ts, src/hubextensions.ts, src/integration.ts
Add express integration to playground
=> feat(playground): add express integration

bindings/cpu_profiler.cc
This could have possibly caused name collisions and ending up reporting wrong functions in parts of the stack.
=> fix(c++): make sure we use unique_id

src/hubextensions.ts
Just better (and actionable) debug logs for when we fail to patch the SDK.
=> feat(skd): add better messaging when we cannot patch the lib

bindings/cpu_profiler.cc, src/cpu_profiler.test.ts
This was running at 1kHz while I was validating the data. It is no longer necessary and we can move to 99hz sampling interval.
=> feat(profiling): adjust sampling frequency

.gitignore, bindings/cpu_profiler.cc, playground/direct_bindings/index.ts, src/cpu_profiler.test.ts
Add the ability to index stacks. This reduces format size and seems to also reduce CPU usage as we are creating less JS nodes.
=> feat(profiling): index stacks

src/hubextensions.ts
=> ref(sdk): remove sdk tag

src/hubextensions.ts
Found the culprit, no longer need this
=> ref(sdk): remove spans

README.md
Before submitting a pull request, please take a look at our
[Contributing](https://github.com/getsentry/profiling-node/blob/main/CONTRIBUTING.md) guidelines and verify:
=> docs: readme semicolon

src/hubextensions.test.ts, src/hubextensions.ts
Aligns with the rest of our SDKs
=> fix(sampleRate): profilesSampleRate and tracesSampleRate are multiplied

package-lock.json, package.json, playground/concurrent_profiling_main_and_workers/index.js, playground/concurrent_profiling_main_and_workers/worker.js, playground/express/index.js, playground/express/index.ts, playground/main_profile/index.js, playground/main_profile/index.ts, playground/main_with_workers/index.ts, src/hubextensions.hub.test.ts, src/index.test.ts, src/utils.ts
This trace_id is 32hex (no dashes) as per https://www.w3.org/TR/trace-context/#version-format
=> fix(uuid): uuid is 32hex in sentry

jest.config.ts, src/hubextensions.hub.test.ts, src/index.test.ts, src/integration.test.ts, src/integration.ts, src/utils.test.ts, src/utils.ts
Drop profiles with <= 1 sample
=> feat(profiling): discard profiles with <= 1 sample

.github/workflows/build.yml, .github/workflows/ci.yml, package.json, src/index.test.ts
The logger creates a ton of noise
=> feat(ci): run jest with --silent

.github/workflows/build.yml
Downgrade ubuntu to 20.04, fixes #93
=> fix(bin): downgrade ubuntu to 20.04

bindings/cpu_profiler.cc
Only mark in_app if it is false, else allow backend to infer it based on path
=> feat(profiling): only mark in_app: false for system code

package.json
=> Add @sentry/core as dep

.github/workflows/build.yml
Before submitting a pull request, please take a look at our
[Contributing](https://github.com/getsentry/profiling-node/blob/main/CONTRIBUTING.md) guidelines and verify:
=> fix(precompile): fix dir sync

bindings/cpu_profiler.cc
use a cache for module parsing
=> perf: use a module cache

README.md, package-lock.json, package.json, test-binaries.entry.js, test-binaries.esbuild.mjs
Remove tracing dependency which is no longer required and add a comment to prebuid-bin
=> deps(tracing): remove tracing dependency

bindings/cpu_profiler.cc, package-lock.json, package.json, src/bindings.test.ts, src/cpu_profiler.test.ts, src/cpu_profiler.ts, src/utils.ts
Our own root_dir detection differs from the one in errors which means code mappings differ (and break)...
=> fix(profiling): remove app_root relative dir detection

esbuild.esm.mjs
Fix for https://github.com/getsentry/profiling-node/issues/160
=> fix: polyfill to level createRequire for esm

scripts/check-build.mjs, scripts/copy-target.mjs
Stop error handling and just throw
=> build: stop error handling and just propagate all errors

bindings/cpu_profiler.cc, playground/express/index.js, playground/main_profile/index.js, src/cpu_profiler.test.ts, src/hubextensions.hub.test.ts, src/integration.test.ts, src/types.ts, src/utils.test.ts, src/utils.ts
Collect heap memory usage at 10hz / every 100ms. 
Initializes a single ticking timer which delegates collecting of memory usage stats to each profile.
=> feat(measurements): collect heap usage

package-lock.json, package.json, src/hubextensions.hub.test.ts, src/integration.ts
Implements preprocessEvent hook implementation for profiles (counterpart to the replay [PR](https://github.com/getsentry/sentry-javascript/pull/9034/files#diff-132075a904d758e2c4ac08f182e4c6e91a1edb58766aed48fbb44e45730b075f))
=> feat(preprocessEvent): emit preprocessEvent for profiles 

bindings/cpu_profiler.cc
Napi will serialize doubles using scientific notation. Cap precision so we avoid that
=> fix(profiling): cap double precision

README.md
I would like to deprecate this repo as well.
=> Add note about profiling-node move
