getsentry/profiling-node

bindings/cpu_profiler.cc
This was wrongly reporting microseconds instead of ns
=> fix(units): report ns to backend

src/hubextensions.hub.test.ts, src/hubextensions.ts, src/index.test.ts
Concurrent transactions with same name were previously silently ignored (default v8 profiler behavior). 
This PR adds a uuid to the transaction name when calling stopProfiling/startProfiling to mitigate that. This is internal and will not show up in the final profile.
=> feat(sdk): use uuid to avoid ignored transactions

bindings/cpu_profiler.cc
Log call site info instead of the function definition.
```
// Comparing results from main and 7aed418 (sizes in B)
sampled: 44269.5 (+13.18%)
cpu_profiler.sampled.json.gz: 2691 (-1.68%)
cpu_profiler.sampled.json.br: 1929 (-0.98%)
cpu_profiler.sampled.json.zst: 2721 (-0.37%)
```
=> feat(profile): log call site info

README.md, binding.gyp, bindings/cpu_profiler.cc, package.json, scripts/compile-bindings.js, src/cpu_profiler.test.ts, src/cpu_profiler.ts, src/integration.test.ts, src/utils.test.ts
Allows changing the default value from kLazyLogging to kEager logging. Added code comments for when that may be preferable. This is an alternative, but less flexible approach to https://github.com/getsentry/profiling-node/pull/51 that should help us achieve a similar outcome without adding init requirements.
=> build(gyp): add compile time flag for profiler logging strategy

benchmarks/integrations/jest/js/base/base.config.js, benchmarks/integrations/jest/js/base/base.env.js, benchmarks/integrations/jest/js/base/base.test.js, benchmarks/integrations/jest/js/base/run.js, benchmarks/integrations/jest/js/profiled/profiled.config.js, benchmarks/integrations/jest/js/profiled/profiled.env.js, benchmarks/integrations/jest/js/profiled/profiled.test.js, benchmarks/integrations/jest/js/profiled/run.js, benchmarks/integrations/jest/ts/base/base.config.ts, benchmarks/integrations/jest/ts/base/base.env.ts, benchmarks/integrations/jest/ts/base/base.test.ts, benchmarks/integrations/jest/ts/base/run.js, benchmarks/integrations/jest/ts/profiled/profiled.config.ts, benchmarks/integrations/jest/ts/profiled/profiled.env.ts, benchmarks/integrations/jest/ts/profiled/profiled.test.ts, benchmarks/integrations/jest/ts/profiled/run.js
We are currently incurring significant overhead in jest tests (30% added time when running on gha), see https://github.com/getsentry/sentry/pull/40183. This adds a reproducible env where we can run benchmarks on a profiled and non profiled env so we can eliminate causes faster.
=> ref(benchmark): add jest benchmark

LICENSE, package.json
I wrongly took this from sentry-javascript repo. Switching to MIT license
=> chore(license): switch to MIT

src/hubextensions.test.ts, src/hubextensions.ts
We are seeing some delays between stopProfiling and transaction.finish. Add temporary spans so we can see if this is a performance penalty from calling to c++ code.
=> ref(sdk): add temporary spans

README.md, binding.gyp, bindings/cpu_profiler.cc
Instead of compile time flags, lets make this based off env variables so we have more flexibility
=> feat(profiling): use env variable instead of compile time

src/utils.ts
The type guard was only checking for undefined, but stopProfiling may return a null profile. This fixes https://github.com/getsentry/profiling-node/issues/63
=> fix(envelope): missmatch in type guard

bindings/cpu_profiler.cc, src/cpu_profiler.test.ts, src/hubextensions.test.ts, src/utils.ts
When deduping stack frames I introduced a bug that would result in the final stacks array to contain holes.
Added a test that reproduces the behavior and fixed the insertion index problem.
=> fix(profile): wrong stack indexing insertion

bindings/cpu_profiler.cc
We were casting to wrong value which lead to losing precision for profiles whose duration exceeded uint32 max
=> fix(timestamps): int64_t

.github/workflows/build.yml, .github/workflows/ci.yml, bindings/cpu_profiler.cc, src/cpu_profiler.ts, src/hubextensions.hub.test.ts
This PR adds support for compiling to node 19 target (fixes https://github.com/getsentry/profiling-node/issues/78)
=> test(build): add node 19 to build matrix

bindings/cpu_profiler.cc, src/utils.ts
Fixes a segfault on gcloud (tested by deploying our own service). Not exactly sure what the exact cause was, but it seems it had something to do with setting a return value before deleting a profile.
=> fix(segfault): fix return value order

src/hubextensions.hub.test.ts, src/utils.ts
Read env from sdk init and pass it along, this was previously missed.
Link in relay https://github.com/getsentry/relay/blob/760a62aeafb8bc69071950624318a7d17ac81087/relay-profiling/src/sample.rs#L142
=> fix(env): read env from sdk

bindings/cpu_profiler.cc, src/cpu_profiler.ts, src/hubextensions.hub.test.ts, src/index.test.ts, src/integration.test.ts, src/utils.test.ts, src/utils.ts
Tested e2e by ingesting a couple profiles from the tests in order to be 100% sure - https://specto-dev.sentry.io/profiling/summary/profiling-node/?project=6625302&statsPeriod=1h&transaction=same-title
=> ref(format): remove transactions array in favor of transaction property

package.json, src/hubextensions.test.ts, src/hubextensions.ts, src/utils.test.ts, src/utils.ts
Add profilesSampler method with similar functionality as tracesSampler. If profilesSampler is set, prefer it's outcome vs profilingSampleRate
=> feat(profiling): add profilesSampler

README.md
Updated readme with correct link to installing `@sentry/profiling-node` dependency
=> docs: update install link for sentry profiling

scripts/check-build.js
=> Check if module exists before loading. Compile if missing

package.json, src/integration.ts
Deletes profile context before sending data to the backend, we keep it locally so we can associate the txn with profile, but delete before sending
=> ref: remove profile context before sending

.github/workflows/build.yml, .gitignore, esbuild.binaries-copy.js, esbuild.cjs.js, esbuild.esm.js, jest.config.ts, package.json, playground/express/index.js, scripts/binaries.js, scripts/check-build.js, scripts/cjs.mod.js, scripts/copy-target.js, scripts/esm.mod.js, src/cpu_profiler.ts, src/hubextensions.hub.test.ts, src/hubextensions.test.ts, src/index.test.ts, src/index.ts, src/utils.test.ts, test-binaries.entry.js, test-binaries.esbuild.js, tsconfig.base.json, tsconfig.cjs.json, tsconfig.esm.json, tsconfig.test.json, tsconfig.types.json
Our bindings require call was fully dynamic so bundlers (only tested esbuild and webpack) could not determine the static set of binaries that they need to copy the binaries for, resulting in MODULE_NOT_FOUND runtime error.
This PR fixes this by hardcoding the set of binaries so that they can be copied to the final bundle - the caveat of this approach is that now all precompiled binaries will be copied. Sadly, the approach is not fully forward compatible as missing env/platform/node variants which are not hardcoded will still have to be manually copied.
To ensure we don't break builds by hardcoding binaries and not providing precompiled binaries, I added a step before creating the final npm tarbal which attempts to build a bundle including our profiling package - this triggers .node files …
=> fix(build): enumerate precompiled binaries

scripts/check-build.mjs
Since version [1.0.0-alpha.6](https://github.com/getsentry/profiling-node/releases/tag/v1.0.0-alpha.6) there's a broken reference to `copy-target.js` script, which has been renominated as `copy-target.mjs`.
This prevents the build from source to complete successfully
=> fix broken reference to copy-target script

src/cpu_profiler.ts
I guess .node imports are not supported in ESM... fixes https://github.com/getsentry/profiling-node/issues/160
=> fix: require instead of import in esm

package.json
This has been causing more headache than it is worth. Tldr, but pure esm cannot import .node files (unknown file extension error) and using createRequire(import.meta.url) breaks bundlers 😭
=> build: drop esm support

scripts/check-build.mjs
This is a fix for #171 and #141. 
The command in recompileFromSource passed to cp.spawnSync uses the && operator to chain multiple npm scripts together. However, && is a shell operator for command chaining and conditional execution.
cp.spawnSync expects a single command as the first argument, making it incompatible with the && operator usage. && is interpreted by the shell, not as part of a single command.
To resolve this, there are two options:
1. Separate npm scripts into individual commands: Execute each npm script separately using cp.spawnSync. This ensures each script is treated as an independent command, eliminating the need for shell operators like &&.
2. Execute a shell command: Invoke a shell (e.g., sh) and pass the entire chain of npm scripts with && as the argument to …
=> fix: Issue fixed for building binary with recompileFromSource

package-lock.json, package.json, src/utils.ts
Before submitting a pull request, please take a look at our
[Contributing](https://github.com/getsentry/profiling-node/blob/main/CONTRIBUTING.md) guidelines and verify:
=> deps(sentry): bump sentry deps

.github/workflows/build.yml, src/cpu_profiler.test.ts, src/cpu_profiler.ts
Cross compile from x86 to arm64 on macos image, doing that from ubuntu causes binaries to throw with mach-o file.
Manually tested by downloading the binaries from GHA and requiring them
=> fix(build): cross compile from x64 to arm

scripts/check-build.mjs, scripts/copy-target.mjs
Catch and re-throw in case spawn cmd fails
=> fix(build): catch spawn err

bindings/cpu_profiler.cc, src/cpu_profiler.test.ts, src/hubextensions.hub.test.ts, src/integration.ts, src/utils.ts
Removing the throw call added in https://github.com/getsentry/profiling-node/pull/187/files#r1316130323 and unblocks #196
I did not manage to find a root cause quickly so I am removing the throw call in order to unblock users (it was added recently). I've looked through the timeout logic and did not find any issues (I have added some more tests). Since nulptr is a valid return from the profiler we should just handle it gracefully anyways
=> fix: dont throw if profiler returns nulptr

README.md
When trying to run the profiler in Nextjs 13+ I've found that I can't edit directly the "externals" because it' being passed as a function, but this setting exists to declare external packages, which looks to be working on my end (local dev, local build and deploying).
https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages
-----
Before submitting a pull request, please take a look at our
[Contributing](https://github.com/getsentry/profiling-node/blob/main/CONTRIBUTING.md) guidelines and verify:
=> Update README.md to include Next.js 13+ bundling

bindings/cpu_profiler.cc
`std::string(char*)` makes a deep copy of the string, but `string.h` provides us with `strcmp` C function to have equality checks between 2 different char pointers.
=> perf: avoid deep string copy

README.md
Add section on rollup and marking package as external
https://github.com/getsentry/sentry-javascript/issues/9750
=> docs: add rollup external config section

bindings/cpu_profiler.cc, package.json
Fix #228 (tested by linking the built module to the reproducible code from issue).
=> fix: cleanup timer and reuse exports

bindings/cpu_profiler.cc
Having a bit of a hard time fixing this, though it seems like this occurs if we attempt to close an inactive handle. Added uv_is_active before calling close.
Fixes #233
=> ref: close handle only if active

package.json
After installing latest version of `@sentry/profiling-node` the types are not detected:
Seems like after recent changes `tsconfig.base.json` uses `outDir: lib/types`
But `package.json` is not updated:
=> fix: update types entry in package.json
